version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update -y; apt dist-upgrade -y; apt install g++ cmake -y
      - run:
          name: Building
          command: source ./script/build.sh
  unittest:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update -y; apt dist-upgrade -y; apt install g++ cmake -y
      - run:
          name: Running unit tests
          command: source ./script/unittest.sh
  systemtest:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update -y; apt dist-upgrade -y; apt install g++ cmake -y
      - run:
          name: Running system tests
          command: source ./script/build.sh; source ./script/systemtest.sh

workflows:
  version: 2
  tests:
    jobs:
      - unittest
      - systemtest
