version: 2.1
jobs:
  build:
    steps:
      - run:
        name: Building
        command: source ./script/build.sh
  unittest:
      - run:
        name: Running unit tests
        command: source ./script/unittest.sh
  systemtest:
      - run:
        name: Running system tests
        command: source ./script/build.sh; source ./script/systemtest.sh
