name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: clone gtest
      run: git submodule update --init --recursive
    - name: unit tests
      run: source ./script/unittest.sh
    - name: system tests
      run: source ./script/systemtest.sh
